### ISSUE TITLE
Feature Request (case insensitive path, global overrides)

### ISSUE THREAD

**Issue by brianwthomas** [jeremydaly/lambda-api#101]
Bear with me if I'm missing something, but when reading docs I couldn't figure out if any of these features are added.

1) Add the ability to handle case insensitivity for the path/URL.  For example /test and /TEST I may want the results to hit the same function.  The ability to add a case insensitivity when adding the API would be awesome instead of having to take the request object and lowercase the path string but not any user data (query strings, etc...)

2) Global Overrides for headers.  It'd be nice to be able to at the start of my function create a global override for things like generating my own requestIds, or specific server side headers I want to be injected in the response globally, or within a specific route.

**Comment by jeremydaly** [comment]
Great suggestions. I'll add them to the roadmap!
