### ISSUE TITLE
Allow disabling of automatic error logging

### ISSUE THREAD

**Issue by mjdickinson** [jeremydaly/lambda-api#102]
We make extensive of exceptions to propagate errors.  The automatic error logging (in catchErrors()) does not meet our needs:
- it does not log metadata attached to an Error object
- all Errors are logged as *fatal*; we'd like more control

It is simple enough to log errors in any way we like in error handling middleware.  However, it would be handy if we could switch off automatic error logging to avoid double logging with *fatal* log entries.  Or maybe lower the severity level.

**Comment by jeremydaly** [comment]
Hi @mjdickinson,

The default logging was meant to add consistency, but your request makes sense. Will add to the roadmap.

Thanks,
Jeremy
