### ISSUE TITLE
Trouble getting Hello World example

### ISSUE THREAD

**Issue by rgillen** [jeremydaly/lambda-api#103]
Have a basic hello world Lambda working, tried to outfit it with your library. All I seem to get is "Internal Server Errors" as soon as I remove your lib it starts work again. Very disappointing 👎 

## handler.js
`const api = require('lambda-api')({ version: 'v1.0', base: 'v1' });`

`api.options('/*', (req,res) => {
  res.status(200).json({})
});`

// Define a route
`api.get('/test1', async (req,res) => {
  return { status: 'ok' }
});`

// Declare your Lambda handler
`exports.handler = async (event, context) => {
  // Run the request
  return await api.run(event, context)
}`

## serverless.yml
`service: scripts

provider:
  name: aws
  region: us-west-1
  runtime: nodejs8.10

functions:
  serverless-api-sample:
    name: ${self:service}-${self:provider.stage}-serverless-api-sample
    handler: handler.router
    timeout: 30
    events:
      - http:
          path: 'v1/{proxy+}'
          method: any`

## Output from Serverless Deploy:

Serverless: Stack update finished...
Service Information
service: scripts
stage: production
region: us-west-1
stack: scripts-production
resources: 11
api keys:
  None
endpoints:
  ANY - https://sbtn93jfjc.execute-api.us-west-1.amazonaws.com/production/v1/{proxy+}
functions:
  serverless-api-sample: scripts-dev-serverless-api-sample
layers:
  None

**Comment by jeremydaly** [comment]
Hi @rgillen,

I'm using this library in 15 production environments and it works perfectly fine. Your code above is defining your `options` route with `app.options()`, but you're declaring `api` when initializing the library. This is likely why you're getting an error, because `app` is not defined.

Try changing `app` to `api` and your code above should work.

**Comment by rgillen** [comment]
I just found that error and fixed it. I was able to get this from AWS console when trying a 'Test' in API Gateway.

Handler 'router' missing on module 'handler'

**Comment by jeremydaly** [comment]
You are exporting your handler function as `handler` in your `handler.js` script, but your `serverless.yml` file is pointing to `handler.router`. Either update your `serverless.yml` to `handler: handler.handler` or rename your export in `handler.js` to `exports.router`.

**Comment by rgillen** [comment]
Thank you for you patience. It seems my original issue was the missing `{proxy+}` in `serverless.yml` I then embarked on a series of cut/paste errors in an attempt to simplify my code and get it to work

**Comment by jeremydaly** [comment]
Glad I could help.
