### ISSUE TITLE
async error handling middleware not working

### ISSUE THREAD

**Issue by mjdickinson** [jeremydaly/lambda-api#107]
I ran into an issue when I tried to convert an error handling middleware function to async.

Stepping through the code in index.js#285
```
      // Execute error middleware
      for (const err of this._errors) {
        if (response._state === 'done') break
        // Promisify error middleware
        await new Promise(r => {
          let rtn = err(e,response._request,response,() => { r() })
          if (rtn) response.send(rtn)
        })
      } // end for
```

If the err function is async, it return a promise, which then causes response.send() to be called with that promise as argument.

I believe the implementation should be the same as used for standard middleware around line 228.

**Comment by jeremydaly** [comment]
Please provide some additional context as well as a code sample. Thanks.

**Comment by tobilg** [comment]
I have the same issue when trying to implement a custom authorization middleware for a proxy integration:

```javascript
api.use((req,res,next) => {
  if (req.headers.authorization) {
    tokenHelper.verifyToken(req.headers.authorization).then(decodedToken => {
      // Assign userId
      req.userId = decodedToken.sub;
      next();
    })
    .catch(err => { // will yield error if token is expired/invalid/etc.
      res.error(401, err.message);
    });
  } else {
    res.error(401, 'Not Authorized');
  }
});
```

This results in 502 errors in the API GW logs:

```text
Received response. Status: 200, Integration latency: 1056 ms
Endpoint response headers: {Date=Wed, 29 Jan 2020 13:43:58 GMT, Content-Type=application/json, Content-Length=4, Connection=keep-alive, x-amzn-RequestId=78673038-13fc-45c4-bd5c-7ae16907d097, x-amzn-Remapped-Content-Length=0, X-Amz-Executed-Version=$LATEST, X-Amzn-Trace-Id=root=1-5e318c1d-62bb201404af02cff146867f;sampled=0}
Endpoint response body before transformations: null
Execution failed due to configuration error: Malformed Lambda proxy response
Method completed with status: 502
AWS Integration Endpoint RequestId : 78673038-13fc-45c4-bd5c-7ae16907d097
```

**Comment by JustinLutsky** [comment]
I'm having the same issue with some authorization middleware. If I do:

      return res.error(401, 'Not Authorized');

Prior to any 'awaits', it responds with the correct 401. However, if I do that after any 'awaits' in the code the result is a 502 timeout.

**Comment by JustinLutsky** [comment]
Fixed my issue by replacing all:

return res.error(401, 'Not Authorized');

with...

return await res.error(401, 'Not Authorized');

**Comment by tobilg** [comment]
@JustinLutsky Thanks, that fixed it for me. @jeremydaly would it eventually make sense to include this in the README?
