### ISSUE TITLE
Using with ALB gives 502 Bad Gateway

### ISSUE THREAD

**Issue by QAnders** [jeremydaly/lambda-api#117]
We've been using `lambda-api` with APIGW for some time and just love it, so first of a massive Thank You!

Now we've been looking at moving our backend API's to an internal ALB instead and started doing tests with using `lambda-api` for it as well.
The ALB works fine and triggers the Lambda but using any valid route we always get `502 Bad Gateway` response from ALB.
Trying with a invalid URI or method `lambda-api` responds correctly, e.g.:
```
{
    "error": "Route not found"
}
```
or
```
{
    "error": "Method not allowed"
}
```
I found some documentation stating that `statusDescription` is required in the ALB response but with or without `statusDescription` it behaves the same...

Any clues on what I can have a look at?

**Comment by QAnders** [comment]
Never mind!

I figured it out, it's the header `Access-Control-Allow-Credentials` that must have a `String` value and not a Boolean `true`, i.e. `res.header('Access-Control-Allow-Credentials', 'true');`  works!

**Comment by jeremydaly** [comment]
Glad you figured it out!
