### ISSUE TITLE
using GraphQL with lambda-api

### ISSUE THREAD

**Issue by mthota15** [jeremydaly/lambda-api#120]
I am trying to use graphql with lambda-api but its not working as expected and seeing following error in graphql IDE. Not sure if lambda-api is able to parse graphql request and response.

{
  "error": "Response not successful: Received status code 500"
}

Here is my code:

handler.js

    const api = require('lambda-api')();
    const { graphql } = require('graphql');
    const schema = require('./schema');

    // ---- Middleware Defination ---- //
    // Add CORS Middleware
    api.use(async (req, res, next) => {
      // Add default CORS headers for every request
      res.cors();
     // Call next to continue processing
     next();
    });

    // ---- Routes Defination ---- //
    api.get('/', async (req, res) => {
      res.status(200).json({ message: 'Welcome to lambda api' });
    });

    api.get('/health', async (req, res) => {
      res.status(200).json({ status: 'ok' });
    });

    api.post('/graphql', async (req, res) => {
      const parsedRequestBody = req.body ? req.body : {};
      try {
         const graphQLResult = await graphql(
         schema,
         parsedRequestBody.query,
         null,
         null,
         parsedRequestBody.variables,
         parsedRequestBody.operationName
         );
        res.status(200).json(graphQLResult);
      } catch (error) {
        throw error;
       }
    });

    export const handler = async (event, context) => {
      return api.run(event, context);
    };

schema.js

    const { GraphQLString, GraphQLObjectType, GraphQLSchema } = require('graphql');

    const schema = new GraphQLSchema({
      query: new GraphQLObjectType({
       name: 'Query',
       fields: {
         Hello: {
           type: GraphQLString,
           resolve: () => {
             return 'Hello world!';
          }
        }
      }
     })
    });

    module.exports = schema;

**Comment by jeremydaly** [comment]
This should work. Can you trace where the error is being thrown from? For example, is the `graphQLResult` being generated correctly, or is if failing before that?

**Comment by mthota15** [comment]
Actually it worked. Thanks for looking into it.
