### ISSUE TITLE
Newest Version broke AWS Lambda 

### ISSUE THREAD

**Issue by Jake-Kuznicki** [jeremydaly/lambda-api#133]
Attempted to spin up a new project using AWS Lambda with v10.3 but I keep getting cannot execute "includes" of undefined in the lambda-api index.js line 259....reverted to the 10.2 and it worked just fine

**Comment by jeremydaly** [comment]
Thanks @Jake-Kuznicki. Checking this out now.

**Comment by jeremydaly** [comment]
Fixed. This was an edge case that happened if you didn't provide any configuration options.
