### ISSUE TITLE
Support for HTTP APIs

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/lambda-api#136]
Announcement here: https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/

Just need to run some tests to see if the even payload is any different.

**Comment by JustFly1984** [comment]
@jeremydaly  Do you have any plans to support websockets lambdas deploy with API Gateway support?

**Comment by jeremydaly** [comment]
I did take a look at supporting it (see #82) and it didn't seem to fit. But I'm investing more time in this library, so I'll take another look.

**Comment by bionicles** [comment]
I really want to use HTTP API with AWS CDK and your lambda api repo jeremy! 

Also want to add some input validation with jquense/yup and ABAC with ramda or some specialized tool

**Comment by malpaso** [comment]
Has anyone confirmed whether this works with HTTP APIs ?

**Comment by MarioVerbelen** [comment]
I'm using that with $default routing to my Authorizer and a lambda integration with the lambda-api as routing (routing is done in the single lambda function)

I had no issues for now (running about a month now)

**Comment by stawecki** [comment]
@malpaso It seems to work fine when configuring the Lambda integration's "Payload format version" to "1.0". It does not work with the default "2.0" format.
(More on payload formats: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)
@MarioVerbelen you're using 1.0, right?

**Comment by MarioVerbelen** [comment]
The format is on V1.0 idd

**Comment by jeremydaly** [comment]
@stawecki, you are correct. The library isn't compatible with the 2.0 payload format. This is being worked on and should be added soon.

**Comment by clarkd** [comment]
I get `Route not found` when using HTTP API (via Serverless Framework). Is there anything special I need to do to get it working?

Notably, were using a custom domain with base path mappings (to a particular stage).

Any pointers to where I can start debugging this?

**Comment by stawecki** [comment]
@clarkd probably best to start with checking the payload. Serialize and log the Lambda event, then fetch the logs using serverless CLI or through CloudWatch.
```js
exports.run = async (event, context) => {
  console.log( JSON.stringify(event) ); // log the event
  return await api.run(event, context)
}
```
You'll be able to see what path is being passed to your Lambda and replicate the issue locally.

**Comment by clarkd** [comment]
@stawecki Thanks - I'll give that a go :) Appreciate the assist.

**Comment by clarkd** [comment]
Hmm, it looks like `lambda-api` is trying to find a route that matches `event.path` rather than, e.g. `event.resource` or `event.requestContext.resourcePath`. The first part of the `path` shown is the stage name (`saas-46-db-wrapper-e`).

```
{
  version: '1.0',
  resource: '/subjects',
  path: '/saas-46-db-wrapper-e/subjects',
  httpMethod: 'GET',
  headers: {
    'Content-Length': '0',
    'Content-Type': 'application/json',
    Host: 'xxxxxxxxxxxxx',
    'X-Amzn-Trace-Id': 'Root=1-5eaa14ac-3b54f0a603745884ce426e2a',
    'X-Forwarded-For': 'xxxxxxxxxxxx',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
    accept: 'application/json'
  },
  multiValueHeaders: {
    'Content-Length': [ '0' ],
    'Content-Type': [ 'application/json' ],
    Host: [ 'xxxxxxxxxxx' ],
    'X-Amzn-Trace-Id': [ 'Root=1-5eaa14ac-3b54f0a603745884ce426e2a' ],
    'X-Forwarded-For': [ 'xxxxxxxxxxxxxxx' ],
    'X-Forwarded-Port': [ '443' ],
    'X-Forwarded-Proto': [ 'https' ],
    accept: [ 'application/json' ]
  },
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  requestContext: {
    accountId: 'xxxxxxxxxx',
    apiId: 'xxxxxxxxx',
    domainName: 'xxxxxxx',
    domainPrefix: 'api',
    extendedRequestId: 'xxxxxxxx',
    httpMethod: 'GET',
    identity: {
      accessKey: null,
      accountId: null,
      caller: null,
      cognitoAuthenticationProvider: null,
      cognitoAuthenticationType: null,
      cognitoIdentityId: null,
      cognitoIdentityPoolId: null,
      principalOrgId: null,
      sourceIp: 'xxxxxxxxxx',
      user: null,
      userAgent: '',
      userArn: null
    },
    path: '/saas-46-db-wrapper-e/subjects',
    protocol: 'HTTP/1.1',
    requestId: 'xxxxxxxxxx',
    requestTime: '29/Apr/2020:23:58:36 +0000',
    requestTimeEpoch: 1588204716949,
    resourceId: 'GET /subjects',
    resourcePath: '/subjects',
    stage: 'saas-46-db-wrapper-e'
  },
  pathParameters: null,
  stageVariables: null,
  body: null,
  isBase64Encoded: false
}
```

Extracted from the above^:
```
path = '/saas-46-db-wrapper-e/subjects'
resource = '/subjects'
requestContext.resourcePath = '/subjects'
```

Notably, when I run this locally using `serverless-offline`, the URL still has the stage in, i.e. `http://localhost:3000/stage/subjects`, but it works as expected, and the event looks like this: 

```
{
	path: "/subjects"
	requestContext: {
		path: "/stage/subjects",
		resourcePath: "/subjects"
		[...]
	}
	[...]
}

```

What do you think? Is this a bug with `lambda-api` or somewhere else?

**Comment by jeremydaly** [comment]
The library doesn’t support HTTP APIs yet. There is a new payload version that needs to be added.

**Comment by stawecki** [comment]
@clarkd  I think that's because "resource" represents the resource path in your API, which could be a proxy resource e.g.: `{ "resource": "/documents/{proxy+}", "path": "/documents/123" }` or in case of the $default route in HTTP API: `"resource": "$default",`.
You can detect the stage by looking at the payload's `requestContext.stage`. It's strange that this is included in the path, as that isn't the case for API GW's "REST API".

I suggest using REST API, until HTTP API is fully supported or only use the default stage, which shouldn't prefix the path.

**Comment by clarkd** [comment]
@jeremydaly This is using payload version 1.0 I believe which @stawecki indicated should work - but I'm prepared that it might not be 100% compatible right now. Happy to help contribute where I can.

@stawecki Yeah, it certainly is strange and like I say, this doesn't happen using serverless-offline so there's an issue somewhere - just not sure who's fault it is! I'll try and spin up a small reproduction, because we've got a fair bit going on in this project that could be contributing to the issue.

As a workaround I can do something like this but it's obviously a little hacky.

```
export const run: APIGatewayProxyHandler = async (event: APIGatewayEvent, context: Context): 
    Promise<APIGatewayProxyResult> => {

    //TODO: Find out why the path includes the stage, it shouldn't... 
    // We fix it by stripping it before passing it to the router
    // See https://github.com/jeremydaly/lambda-api/issues/136
    // See https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html
    if(event.path.startsWith(`/${event.requestContext.stage}`)) {
        event.path = event.path.substring(event.requestContext.stage.length + 1);
    }

    // Send the request through our router
    return api.run(event, context);
};
```

**Comment by ryanpagel** [comment]
Any update?  I'd really like to use this with HTTP APIs.

**Comment by wigsaparelli** [comment]
> @stawecki, you are correct. The library isn't compatible with the 2.0 payload format. This is being worked on and should be added soon.

Hi, any update on when 2.0 payload format support is coming?

**Comment by mgregory73** [comment]
You can see how the Serverless team is using HTTP API in their express component by re-mapping the event. https://github.com/serverless-components/express/blob/master/src/_express/handler.js#L11

I've done the same sort of thing and it works with lambda-api, but official adoption would be so much better. The other big thing with HTTP API is that there is no compression out of the box. If anyone has solution for that, please share. The npm compression middleware doesn't seem to work as far as I can tell. Anyhow, looking forward to this enhancement and thanks for all you've contributed.

**Comment by QAnders** [comment]
First off, thanks for your hard work! Much appreciated!

Then... any update on this?
It would be really nice to get HTTP API v2.0 events working...

**Comment by jeremydaly** [comment]
@QAnders, sorry for the delay. Payload V2 support is in the v0.11 branch, but I'm still trying to rework the execution stacks. There were some known errors that I've been trying to fix, but keep getting pulled away to other things. I'll try and shift focus and get it out this week.

**Comment by QAnders** [comment]
Nice! Thanks so much!

For anyone waiting I added the below in my `handler.js` to be able to continue testing:

```
  // lambda-api doesn't support v2.0 of HTTP API, remap the route!
  // HTTP API v2.0 adds the `stage` to the path so remove it as v1.0 omits the stage
  event.path = event.path || event.requestContext.http.path.replace(`/${event.requestContext.stage}`, '');
  event.httpMethod = event.httpMethod || event.requestContext.http.method;
```

**Comment by wigsaparelli** [comment]
Is payload V2 support now available?  Thanks

**Comment by brandonwestcott** [comment]
Would it be possible to cut https://github.com/jeremydaly/lambda-api/commit/13d6efc113d435785a45209c10b108995e70470b as its own release so we can get this feature public?

**Comment by benheymink** [comment]
@jeremydaly Any update on this? Any help needed?

**Comment by jeremydaly** [comment]
v2 payload support was added in v0.11. Let me know if you are having issues.
