### ISSUE TITLE
api.register method isn't found with typescript usage

### ISSUE THREAD

**Issue by y-udaykiran96** [jeremydaly/lambda-api#137]
When I'm using this package with typescript, I'm not getting the api.register(route, opts) method under the package. It works fine with nodejs code, but not with the typescript with nodejs.

When I explore the index.d.ts file of this source, I didn't find any type definition for register method under API class.

Please help me using register method with typescript

**Comment by spinlud** [comment]
Same behaviour:

```
import API from 'lambda-api';

const api = API({
    logger: {
        access: true,
        stack: true
    }
});

api.register(...) // <-- register is not present in index.d.ts
```

**Comment by jeremydaly** [comment]
Thanks. Will add it in.

**Comment by JustinLutsky** [comment]
I don't believe there is type definition for api.routes() either.

**Comment by SergKam** [comment]
`req.namespace` also missing

**Comment by stawecki** [comment]
Hi all,
if you could have a look at my bulk PR for these, it would be great. It's been a while, so I'm hoping this will help Jeremy merge these sooner. I'd appreciate a second opinion too.
Just go through the changes and leave your review: https://github.com/jeremydaly/lambda-api/pull/148
I've been using this update in production, so far so good on my end.
Thanks!

**Comment by stawecki** [comment]
Thanks Jeremy! TS users: Reviews still appreciated. Try compiling using latest npm package. File diffs available here: https://github.com/jeremydaly/lambda-api/pull/148/files
