### ISSUE TITLE
Example of how to use with individual lambdas vs monolithic

### ISSUE THREAD

**Issue by sweeetland** [jeremydaly/lambda-api#146]
Hey Jeremy, this looks awesome.

Is there a way to use lambda-api with individual lambdas vs the monolithic approach?

Thanks, James.

**Comment by jeremydaly** [comment]
Absolutely! If you want to allow API Gateway or ALB to handle your routing, you can just specify a method without a route:

```javascript
api.post((req,res) => {
  // do something for ALL post requests
})
```

This method would be called for all post requests that were routed to your Lambda function.

**Comment by sweeetland** [comment]
Thanks for such a prompt reply and for your hard work on this.

Looking forward to trying this out.
