### ISSUE TITLE
Missing multiValueQuery in Request type

### ISSUE THREAD

**Issue by gakinson** [jeremydaly/lambda-api#159]
Hello,

I am trying to find multiValueQuery in your Request type but I am only able to find query. Is this intention or is it missing?

Thank you

**Comment by MarioVerbelen** [comment]
If I understand you want something like url?foo=one,two,three

I have such thing and do a split of the value where I need it
split by ',' or '-' thats very flexible

**Comment by jeremydaly** [comment]
`multiValueQuery` is available on the request object.

**Comment by gakinson** [comment]
I am not seeing in in here https://github.com/jeremydaly/lambda-api/blob/master/index.d.ts#L107-L159

**Comment by jeremydaly** [comment]
It looks like it's missing from the TypeScript definition file. It is available on the object, however. Can you submit a PR?

**Comment by gakinson** [comment]
> It looks like it's missing from the TypeScript definition file. It is available on the object, however. Can you submit a PR?

is the type just a 

```
{
      string: string[] | undefined
}
```

**Comment by gakinson** [comment]
https://github.com/jeremydaly/lambda-api/pull/160

**Comment by gakinson** [comment]
OOC, do you have any idea on when your next release will be?

**Comment by gakinson** [comment]
Has been merged in
