### ISSUE TITLE
Register new route getting error 

### ISSUE THREAD

**Issue by jebricker** [jeremydaly/lambda-api#162]
Setting up multiple routes from base 

```
/ Require and init API router module
const app = require('lambda-api')({  base: 'rcubed',logger: true })

app.register(require('./productTypeRoutes'),{prefix: '/producttype'})
```

When attempting to access any route I get this error on the register line 

```
"errorType": "TypeError",
    "errorMessage": "fn is not a function",
    "stack": [
        "TypeError: fn is not a function",
        "    at API.register (/var/task/node_modules/lambda-api/index.js:481:5)",
        "    at Object.<anonymous> (/var/task/routes/routesHandler.js:4:5)",
        "    at Module._compile (internal/modules/cjs/loader.js:1137:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)",
        "    at Module.load (internal/modules/cjs/loader.js:985:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:878:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1025:19)",
        "    at require (internal/modules/cjs/helpers.js:72:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)"
    ]
}
```
Serverless:
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.20
nodeJS 12x

**Comment by stawecki** [comment]
@jebricker can you also provide the productTypeRoutes.js file or at least a sample of it to see its structure?

**Comment by jebricker** [comment]
A basic route.  I will repeat that the error is being thrown at the register call.  It is not making it to the routes.

```
app.get('/getallactiveproducttype', async(req, res) =>{
    console.log('Get all active product type router')
    let result = await productType.getActiveProductTypes();
    return result;
})
```

**Comment by stawecki** [comment]
Are you exporting the routes inside a function that provides the api object? Like this:
`productTypeRoutes.js` sample
```
module.exports = (api, opts) => {
   api.get('/getallactiveproducttype', async(req, res) =>{
       console.log('Get all active product type router')
       let result = await productType.getActiveProductTypes();
       return result;
   })
}
```

**Comment by jebricker** [comment]
Thanks, That solved the error.  Now can't find the route
Is this the correct setup in the serverless.yaml?
```
productType-api:
    handler: routes/routesHandler.productTypeRouter
    events:
      - http:
          path: 'rcubed/producttype/{proxy+}'
          method: any
```

**Comment by stawecki** [comment]
In serverless you should point the `handler` at your main lambda file, not the routes file. Your lambda handler, which loads the lambda-api module will parse the HTTP event object and pass it to the correct route. The routes file itself, will not be able to process the unparsed HTTP payload.

**Comment by jebricker** [comment]
RoutesHandler file has no routes.  Just the code from the handler from the api.  I can register all the routes in the same file and have it be routed.  

```
const app = require('lambda-api')({  base: 'rcubed',logger: true })

app.register(require('./productTypeRoutes'),{prefix: '/producttype'})
//----------------------------------------------------------------------------//
// Main router handler
//----------------------------------------------------------------------------//
exports.productTypeRouter = (event, context, callback) => {

    app.routes(true);
    // !!!IMPORTANT: Set this flag to false, otherwise the lambda function
    // won't quit until all DB connections are closed, which is not good
    // if you want to freeze and reuse these connections
    context.callbackWaitsForEmptyEventLoop = false

    // Run the request
    app.run(event,context,callback)

} // end router handler
```

The logging only shows one route.  The others are blank in the logs

2020-09-28T12:25:38.472Z	undefined	INFO	╔════╤════╗
║  [1mMETHOD[0m  │  [1mROUTE[0m  ║
╟────┼────╢
╚════╧════╝

2020-09-28T12:25:38.491Z	8e470ed0-d247-4320-b7b3-4bf13b047480	INFO	╔══════════╤═══════════════════════════════════════════════════════════════════════════════════╗
║  [1mMETHOD[0m  │  [1mROUTE                                                                          [0m  ║
╟──────────┼───────────────────────────────────────────────────────────────────────────────────╢
║  POST    │  /rcubed/producttype/updateproducttype/:product_type_id/:product_type_nm/:active  ║
╚══════════╧═══════════════════════════════════════════════════════════════════════════════════╝

**Comment by jebricker** [comment]
Thank you for your help.  I was able to figure out the problem
