### ISSUE TITLE
Add support for multiple params between slashes

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/lambda-api#17]
The following should be supported to allow for more complex URL patterns.

```javascript
api.get('/example/:lat-:lng/radius/:r', (req,res) => { })
```

**Comment by jeremydaly** [comment]
Need to think about this more. This would be incredibly slow given the way route traversal works. Not sure if it is even that common of a use case. The above example could be accomplished with a standard parameterized path and then could parse the pattern.

Let me know if anyone really needs this.

**Comment by tolidano** [comment]
this seems more consistent and just as good, if not better than the pattern above:
`api.get('/example/lat/:lat/lng/:lng/radius/:r', (req,res) => { })`

**Comment by jeremydaly** [comment]
Closing this for now as I don't think there is enough interest. We'll revisit if the issue comes up again.
