### ISSUE TITLE
Best way to send compressed response

### ISSUE THREAD

**Issue by joelrwilliams12** [jeremydaly/lambda-api#170]
I don't see any options for returning compressed (gzip'd) data.

Does such a thing exist?
Can you run compression middle-ware similar to express?
Or do I just need to roll my own using zlib?

**Comment by kevin-miles** [comment]
@joelrwilliams12 0.10.7 now has this built in.

Check out the PR here: https://github.com/jeremydaly/lambda-api/pull/178

Or now the documentation should be updated on how to approach.

**Comment by joelrwilliams12** [comment]
Works great, thanks!
