### ISSUE TITLE
TS: Logger type does not support Additional Info

### ISSUE THREAD

**Issue by jaimalchohan** [jeremydaly/lambda-api#199]
The LoggerFunction doesn't allow a additional info to be passed in

LoggerFunction: https://github.com/jeremydaly/lambda-api/blob/main/index.d.ts#L62
Additional info in README: https://github.com/jeremydaly/lambda-api#adding-additional-detail

This means that in my typescript project, I can't pass a string or object that has additional info to be logged. 
I don't know enough about TS to suggest a fix, so any pointers would be superb.

**Comment by smashercosmo** [comment]
@jeremydaly can we get one of these PRs merged?

**Comment by naorpeled** [comment]
Hey,
I've merged one of the PRs that resolves this,
will release the change soon.
