### ISSUE TITLE
Is this project active? 

### ISSUE THREAD

**Issue by then3rdman** [jeremydaly/lambda-api#202]
First off, this project looks amazing! However there seems to be a lot of open PRs and issues (some almost a year old).

Is this project still actively maintained? If I decide to use this library I will very happily be contributing but don't want to commit to a project that might have been left behind.

Thanks for any responses on advanced!

**Comment by jeremydaly** [comment]
Yes, the project is active with quite a bit of usage. Most of the PRs have been TypeScript related and require some attention. I am the sole maintainer and have been extremely busy with my full-time job over the last year+, but I am shuffling things around to get some more time put into my open source projects. Any help is always appreciated.

**Comment by then3rdman** [comment]
Awesome! I would be using TS so would be more than happy to jump in and help out where possible
