### ISSUE TITLE
Is the project maintained

### ISSUE THREAD

**Issue by napter** [jeremydaly/lambda-api#211]
Hi,

First of all thank you Jeremy for this project and dynamodb toolbox. Both are incredibly useful tools. I was wondering if this project is still maintained. 

What other routing packages / middleware are people using?

**Comment by cshenrik** [comment]
I really enjoy using lambda-api (thank you for the awesome work, @jeremydaly!), but like the OP, I’m worried that it is no longer maintained.

I would also like to know if there are alternatives with a larger community. I have on my TODO to give [Middy’s http router](https://middy.js.org/docs/routers/http-router)  a spin.

**Comment by naorpeled** [comment]
Hey @napter,
thanks for creating this issue, you're awesome 😎 

I'll be starting to maintain this project today.
Will start by going over the pull requests and see what can be merged and then start to resolve issues that don't have PRs attached to them.

**Comment by dolsem** [comment]
@napter @cshenrik I created a fork for single route functions, aiming to simplify internal logic, fix issues and add better TypeScript support. It's fully tested and published to npm, I'd love feedback on it! https://github.com/dolsem/simple-lambda-api

**Comment by napter** [comment]
@dolsem it's not for my use case, routing is the primary reason I use Lambda-API
