### ISSUE TITLE
peerDependencies appear to make packaged Lambda much bigger

### ISSUE THREAD

**Issue by ammulder** [jeremydaly/lambda-api#241]
Would it be possible to omit the peerDependencies (S3) from `package.json`?  The S3 client installation is blowing up my final Lambda from 300 kB to 3 MB, and it kind of defeats the "no dependencies" benefit of lambda-api.  (My lambda doesn't use S3.)

**Comment by ammulder** [comment]
In this case I can run with `legacy-peer-deps=true` in `.npmrc` to avoid the bloat, but I'm not sure that will always be the case (depending on whether other packages used by the Lambda have truly needed peer dependencies).

**Comment by naorpeled** [comment]
Hey @ammulder 

sorry for the delayed response.

Are you using any bundler?
If so you should be able to mark these dependencies as "external" in order to make sure they don't reach your final bundle but would still allow you to use lambda-api properly without any issues

**Comment by naorpeled** [comment]
Hey @ammulder,
I'm closing this issue for now but feel free to ping me if you want me to re-open it≈.
