### ISSUE TITLE
Typescript documentation is out of date - createApi() no longer parses

### ISSUE THREAD

**Issue by croconut** [jeremydaly/lambda-api#253]
i was forced to start using below, as of TS 4.5

``` ts
import createAPI, { NextFunction, Request, Response } from 'lambda-api';

const api = createAPI.default();

```

createAPI is no longer directly callable

**Comment by naorpeled** [comment]
Hey @croconut,
sorry for the huge delay.

This is no longer an issue within the latest versions.
I'll be closing this issue, but feel free to ping me if you need anything.
