### ISSUE TITLE
Should own types for typescript support

### ISSUE THREAD

**Issue by croconut** [jeremydaly/lambda-api#254]
For typescript lambdas that use this library and don't use aws-lambda, we end up having this extra, unused dependency. I resolve by marking it external for my bundler and not including it, but it would make sense and is more user-friendly to inline these types to the index.d.ts file. 

my current workaround: 

``` js
// in package.json
"build": "esbuild index.ts --bundle --external:aws-lambda --tree-shaking=true --format=cjs --platform=node --target=node16 --outfile=./build/index.cjs"

```

**Comment by naorpeled** [comment]
Hey @croconut,
sorry for the huge delay.

We have `@types/aws-lambda` as a dev-dependency,
this should not affect your production bundle 🙏 

I'll be closing this issue, but feel free to ping me if you need anything
