### ISSUE TITLE
as of v1.0.1, node_modules size increased significantly

### ISSUE THREAD

**Issue by joelrwilliams12** [jeremydaly/lambda-api#258]
By adding AWS packages as peerdependencies, the node_modules folder has increased from 164K to 8.5MB.

To keep Lambda load-times quick and to be able to edit code in Lambda, I typically install lambda-api@1.0.0.

However, this means that I don't get future bug fixes.

Is there a way to install the latest version of lambda-api and then clean out some of the unneeded packages?

**Comment by naorpeled** [comment]
Hey @joelrwilliams12,
if you're using any bundler, you should be able to mark AWS packages as external dependencies which means that they would not be a part of your bundle.

**Comment by joelrwilliams12** [comment]
Thanks for the suggestion.
