### ISSUE TITLE
Open API Schema

### ISSUE THREAD

**Issue by kinesra75** [jeremydaly/lambda-api#263]
Hi All,

Is there a way to generate an openAPI schema based on api object ? Can we add extra comment / parameter on the route declaration that we can retrieve on open api schema.

Thanks.

Sebastien B.

**Comment by naorpeled** [comment]
Hey @kinesra75,
I think [this library](https://github.com/lukeautry/tsoa), should do the trick.

Closing this as completed because it's not a part our roadmap.
Feel free to ping me if you need anything.
