### ISSUE TITLE
TypeScript Definition File

### ISSUE THREAD

**Issue by matt-filion** [jeremydaly/lambda-api#28]
Its not uncommon to use TypeScript over top of node.js and being able to reference a TypeScript model would help a ton when using lambda-api in that context.

**Comment by chanlito** [comment]
@matt-filion totally agree, if only there's a tool to generate some d.ts files from existing JS code that'd would be helpful.

**Comment by matt-filion** [comment]
You could always do the inverse, write in TypeScript and let it generate JS... :-) I kid. 
TypeScript definitions are fairly easy to keep up to date as they only expose public structures and functions.

**Comment by jeremydaly** [comment]
Ha, definitely don't want to convert this to TypeScript, but the definition file would make sense.

**Comment by abmohan** [comment]
@jeremydaly - I'm going to take a stab at this. 

Would you mind a pull request to the repo with the typings, or would you prefer they be uploaded to DefinitelyTyped?

**Comment by jeremydaly** [comment]
@abmohan, I think a pull request including the .d.ts files would be awesome!

**Comment by abmohan** [comment]
I'm on it! To the v0.8.0 branch?

**Comment by jeremydaly** [comment]
Yes, that would be great.

**Comment by Wintereise** [comment]
@abmohan Any updates on this? Just curious.
