### ISSUE TITLE
Allow for multiple methods in METHOD call

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/lambda-api#32]
Was thinking that you could define a route for multiple methods using an array of methods in a `METHOD` call.  For example, `api.METHOD([ 'post', 'put' ], '/some/path', (req,res)=> {})`

This would be similar to the idea of an `any()` convenience method, but would restrict the allowable methods.

**Comment by jeremydaly** [comment]
Implemented. I'm looking the methods here, but since most instances just have 1, there should be no performance impact.

**Comment by jimsorock** [comment]
Hi Jeremy, sorry for commenting on a closed issue, but does the typescript definition to support this just need to be updated?
