### ISSUE TITLE
API Gateway alternative

### ISSUE THREAD

**Issue by erdii** [jeremydaly/lambda-api#37]
Hey :) Cool library!

Would it be possible to use https://github.com/coopernurse/caddy-awslambda instead of API Gateway in front of lambda?

I guess some work would have to be done, bc the request envelope formats for the two "proxies" differ.

Do you think this is easy to integrate? I would be happy to supply a pull request with all needed changes/extensions 👍

**Comment by jeremydaly** [comment]
Hi @erdii,

It's already possible to use alternative gateways with Lambda API. You will just have to modify the `event` before passing it into the `.run` method. Caddy Server also requires a different `reply`, so this can be done by short-circuiting the `callback` method:

```javascript
// Declare your Lambda handler
module.exports.handler = (event, context, callback) => {

 let _event = event => {
  // Convert the Caddy Server event into AWS Lambda Proxy format
}

let _callback = reply => {
 // Convert Lambda API response into Caddy Server reply format
}

  // Run the request
  api.run(_event, context, _callback)
}
```

You could build a plugin for this and give users methods to do the two conversions and simply require the dependency. I'd like to keep the core code as simple and lightweight as possible, so trying to support multiple "proxies" could get a bit complicated and messy.

Thanks for the suggestion and your interest. I'd gladly link to a plugin (or a gist of the conversion code) if you want to supply that.

Thanks,
Jeremy

**Comment by erdii** [comment]
very cool @jeremydaly! I will write a plugin that does exactly what you described.

**Comment by jeremydaly** [comment]
Great! Ping me when it's done and I'll post a link. Thanks!

**Comment by erdii** [comment]
Sadly our company decided against using lambda-api because the project has "only" 2 devs and is not very old. We will use https://github.com/awslabs/aws-serverless-express, BUT the remapping from caddy's envelope format to the api-gateway format should be the exact same thing.

Will ping you definitely!

**Comment by jeremydaly** [comment]
No worries. This library is still early, so there is still much to do. I'd be curious to see some benchmarks with aws-serverless-express and how the dependencies affect cold start and execution times.
