### ISSUE TITLE
Request continues after res.json()? 

### ISSUE THREAD

**Issue by nmodi** [jeremydaly/lambda-api#44]
I'm thinking this may be an async issue with dynamo db, but I'm not sure. Here is the offending function: 

```
import shortid from 'shortid';
import dayjs from 'dayjs';

import dynamoDb from './db';
import validate from './schemas';

export const create = (req, res) => {
    const data = req.body;

    const validation = validate(data);
    if (validation.error) {
        console.error('Validation error in creating project resource.');
        res.status(400).json({
            message: 'Validation error.',
            error: validation.error
        });
    }

    const {title, subject, abstract, plan, status} = data;
    const timestamp = dayjs().toISOString(); 
    const project = {
        id: shortid.generate(),
        timestamp,
        title,
        subject,
        abstract,
        plan,
        status
    };

    const params = {
        TableName: process.env.DYNAMODB_TABLE,
        Item: project
    };

    // write the todo to the database
    dynamoDb.put(params, error => {
        // handle potential errors
        if (error) {
            console.error(error);
            res.status(501).json({message: 'error', error});
        }

        res.status(201).json(params.Item);
    });
};

export default create;
``` 

(using babel/webpack for import/export syntax) 

main app code is here:

```
import LambdaApi from 'lambda-api';

import list from './list';
import create from './create';

const app = LambdaApi({base: 'aegis'});

app.use((req, res, next) => {
    res.cors();
    next();
});

app.get('/projects', list);
app.post('/projects', create);

// Default Options for CORS preflight
app.options('/*', (req, res) => {
    res.status(200).json({});
});

export const listener = (event, context, callback) => {
    context.callbackWaitsForEmptyEventLoop = false;
    app.run(event, context, callback);
};
```

For some reason, objects are still getting stored in the database even if they fail validation (and the correct 400 response is sent back). The request is supposed to stop there when you use the res.json() callback, correct? used the sample api as a starting point for what it's worth. 

Any ideas?

**Comment by jeremydaly** [comment]
Which version are you using?

**Comment by nmodi** [comment]
`"lambda-api": "^0.6.0",`

**Comment by jeremydaly** [comment]
@nmodi, I see the problem. Yes, `res.json()` triggers the callback, but doesn't necessarily terminate script execution. Looking at your code, I see two ways to solve this.

1. You can add an `else` statement after your `if (validation.error) {` code block. This would stop the DynamoDB code from executing.
1. You can add a `return` in front of your `res.status(400).json(...` error. This should also stop execution.

Please let me know if that helps.

**Comment by nmodi** [comment]
Got it, that makes sense. I was confused by this line in the documentation: "NOTE: Middleware can use either callbacks like res.send() or return to trigger a response to the user. Please note that calling either one of these from within a middleware function will terminate execution and return the response immediately." 

But I see now you were talking strictly about middleware there not routes. 

Thanks for the quick responses!

**Comment by jeremydaly** [comment]
Sorry it was confusing. I'll note this and make sure that I update the documentation to be more clear.
