### ISSUE TITLE
Downloaded zip files result in Base 64 encoded files.

### ISSUE THREAD

**Issue by nathan-osg** [jeremydaly/lambda-api#54]
First of all, just wanted to say nice work! It's nice to have such a streamlined library for use within a Lambda!

I'm trying to use the library for some downloading of binary files from S3... usually Zip file. This was incredibly easy to get set up! And yes, I did follow the instructions to enable binary mode by adding */* in API Gateway.

The problem I am having is that I can't unzip the file after I have downloaded it as it is still base64 encoded. I can decode it manually and then unzip it, so I do know that this is the problem.

I'm trying to understand the reason for the base64 encoding... we should be able to download non-encoded files. It seems that the reason this encoding was performed is some requirement in API Gateway, is that the case? Maybe your Integration has CONVERT_TO_BINARY set?

I'm trying to read the AWS [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html) to figure out if that needs to be set... Per that link: 

"For API Gateway to pass binary payloads, you add the media types to the binaryMediaTypes list of the RestApi resource **OR** set the contentHandling properties on the Integration and the IntegrationResponse resources."

So, does CONVERT_TO_BINARY really need to be set? And, if not, should "lambda-api" be encoding it as Base64?

**Comment by jeremydaly** [comment]
Hi @nathan-osg,

I just tried a zipped file through S3 and I didn't have any problems with the encoding. Lambda API doesn't use the CONVERT_TO_BINARY option because it relies on API Gateway's base64 support for binary files. The response from Lambda API sets `isBase64Encoded` to `true` for all file transfers. API Gateway should then decode the file and deliver it properly to your browser.

Can you try downloading a non-zip file and see if you have the same issue?

**Comment by nathan-osg** [comment]
Sure! I just tried a GIF and got the same result. It could not be opened until after I manually Base64 decoded it.

The lambda-api code clearly seems to be doing the encoding, but it seems to me that your API gateway is decoding your binary whereas mine is not for some reason. So, I'm wondering if we have a difference in our gateway. 

Do you have anything set on your method response?

**Comment by jeremydaly** [comment]
The only configurations should be setting the integration type to Lambda Proxy and adding `*/*` for the binary media types.

How are you standing up the API Gateway? Manually, or with a framework like Serverless or SAM?

**Comment by jeremydaly** [comment]
@nathan-osg, I just created a brand new API from scratch and just added the binary media type `*/*` and then redeployed the API and the base64 encoding/decoding is working. I used the Serverless framework to deploy everything.

**Comment by NateRedding** [comment]
Cool, thanks for the effort to find a solution here. I haven't gotten a chance to revisit this really... been busy with my other job. That said, a basic redirect solution will not work for me as I need additional authorization controls beyond that provided by S3. This "signed url" approach looks quite intriguing though... I may have to investigate that path some more.
