### ISSUE TITLE
Add streaming support  for binary files to sendFile()

### ISSUE THREAD

**Issue by nathan-osg** [jeremydaly/lambda-api#55]
As I was looking into a separate issue where my files are coming out base64 encoded, I was browsing the sendFile() code. I noticed that when retrieving a file from S3, it retrieves the whole object before sending it back to the requester:

`let data = await S3.getObject(params).promise()`

This may be fine for smallish files, but for large files, this could potentially consume a TON of memory. A more efficient approach is to start sending data back to the client as soon as you start getting it from S3. 

With S3 you can get a Node.js stream as so:

`s3.getObject(params).createReadStream()`

See also: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/requests-using-stream-objects.html

**Comment by nathan-osg** [comment]
Grr... looking a little further, it would seem that the JS version of Lambda may not have a way to return a stream back to API gateway, however. :(  (The Java version does)

https://stackoverflow.com/questions/39381139/how-to-stream-aws-lambda-response-in-node

**Comment by nathan-osg** [comment]
Just FYI, I posted to the AWS forums asking if there were any plans to add stream input/output support to Lambda on Node... not sure if it will bear any fruit. 

https://forums.aws.amazon.com/thread.jspa?threadID=286462

This is a pretty big bummer for me... :(

**Comment by jeremydaly** [comment]
Yes, Lambda doesn't support file streaming to API Gateway. Lambda API isn't really designed for loading really large files anyway. However, if you did need to let users download large files from S3, you could use Lambda API to generate access tokens and then use `res.redirect()` to send them to the S3 bucket URL.

**Comment by jeremydaly** [comment]
I did a little more research, and you can use `getSignedUrl()`, documented here: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

This would create a temporary link that you could then redirect the user to. I think I'm going to add this as a feature.

**Comment by Noob7** [comment]
The whole point of sending files through lambda is to get some additional functionality. In my case I need to collect all files in a folder and zip them before sending. Is there a way to do it via a lambda without having to load all files in the lambda memory :(
