### ISSUE TITLE
async 404

### ISSUE THREAD

**Issue by GuidoNebiolo** [jeremydaly/lambda-api#63]
Hi,
I'm trying to send a 404 status as response of an endpoint using async and await
```
    api.get('/:id', async (req, res) => {
        res.status(404)
    })
```
 but I'm receiving a 200 response.

Using the example from the readme I'm getting a 500 error
```
    api.get('/users', (req,res) => {
        res.status(401).error('Not Authorized')
    })
```

If I use another way to write the error it works:
```
    api.get('/:id', async (req, res) => {
        res.error(404, "Not Found")
    })
```

**Comment by jeremydaly** [comment]
Thanks for the report. There is another related bug #62, that seems to be causing similar issues.

**Comment by jeremydaly** [comment]
@GuidoNebiolo, after looking at this in more depth, the behavior is expected. 

In the first example, you need to use the `.send()` method to trigger a response, or `return` something in order for the response to be generated.

```
api.get('/:id', async (req, res) => {
  res.status(404).send
})

// OR

api.get('/:id', async (req, res) => {
  res.status(404)
  return 'something'
})

I'm sorry to say that the example in the documentation is outdated, so I will make sure that is updated. Because of the way Lambda API handles errors (consistently across triggered and caught errors), the `.status()` value is overridden internally. You either need to use the `res.error(404, 'Not Found')` version, or use something like the `.send()` method with your own error message.
