### ISSUE TITLE
Trouble with middleware

### ISSUE THREAD

**Issue by afterthought** [jeremydaly/lambda-api#64]
Hi,

Tried setting up a simple example and had trouble with middleware. Can't get middleware example from documentation to work:

    api.use((req,res,next) => {
        if (req.headers.authorization === 'some value') {
            req.authorized = true
            next() // continue execution
        } else {
            res.status(401).error('Not Authorized')
        }
    })

What happens is when I should see a 401 response I instead see a 502 response. I debugged it for hours and could only determine that it seems like a 2nd response/body is being set or it's going through the final callback a second time by mistake. I think the 502 comes from API Gateway not parsing the response. I was testing using API Gateway Local Runner on Cloud9. If I move the "res.error" line of code into a route the proper 401 response is returned. Until we get this fixed, that's my temporary workaround. Any ideas?

**Comment by jeremydaly** [comment]
This appears to be related to bug #62. It is being investigated.

**Comment by jeremydaly** [comment]
@afterthought, I've identified the error having to do with using `async/await` for the main handler. The example works using the callback approach. 

Working on a patch now.
