### ISSUE TITLE
Support for custom serializers (response)

### ISSUE THREAD

**Issue by Wintereise** [jeremydaly/lambda-api#67]
Currently, it appears an implicit `JSON.stringify` is being used. We internally use https://github.com/typestack/class-transformer to precisely control how something is serialized.

Can we get a hook to override the default serialize function please? I tried feeding it already serialized content, but that simply leads to double JSON serialization.

**Comment by jeremydaly** [comment]
Hi @Wintereise, I think this makes sense. I will add it to the roadmap.

**Comment by jeremydaly** [comment]
Hi @Wintereise, I'm hoping to push a new release in the next few weeks.
