### ISSUE TITLE
Discreet error types instead of blanket "Error"

### ISSUE THREAD

**Issue by Wintereise** [jeremydaly/lambda-api#68]
Due to the reliance on blanket 'Error,' for example (request.js -> parseRequest()):

>       throw new Error('Method not allowed')
>       throw new Error('Route not found')

The only way to differentiate these two (and others) for example on a custom error handling middleware is via string parsing (which has no guarantee of always remaining the same).

Would it not be a good idea if we had some custom types that we could run `instanceof` on for these things? I understand that the list of errors is not very big.

**Comment by jeremydaly** [comment]
Thanks for the suggestion. There are only a few errors, but this probably makes sense.

**Comment by jeremydaly** [comment]
Added five error types to v0.9:

```
RouteError
MethodError
ResponseError
ConfigurationError
FileError
```

**Comment by Wintereise** [comment]
Sounds good @jeremydaly , thank you!
