### ISSUE TITLE
Add support for multi-value query parameters

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/lambda-api#72]
AWS recently announced support for multi-value parameters in Amazon API Gateway (https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/).

**Comment by jeremydaly** [comment]
A PR for this was merged into the v0.10.0 branch.

**Comment by GuidoNebiolo** [comment]
opened a new pull request adding test cases

**Comment by jeremydaly** [comment]
I broke this out into `res.query` and `res.multiValueQuery` so that devs don't need to test for arrays. API Gateway sets the `multiValueQueryStringParameters` for *ALL* query string parameters, so you can always access the latter as arrays.
