### ISSUE TITLE
Add support for multi-value headers

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/lambda-api#73]
AWS recently announced support for multi-value parameters in Amazon API Gateway (https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/).

**Comment by GuidoNebiolo** [comment]
opened a pull request

**Comment by GuidoNebiolo** [comment]
My first idea was the same, but moving to a separate property complicate the logic of getting or deleting the value of one header.
Moreover with this implementation we can be sure that will not be possible to set different values for the same header.
Don't you thing this?

**Comment by jeremydaly** [comment]
For headers I agree. I was doing this late last night and was actually referring to the multi-value query parameters. 🤦🏻‍♂️

I need to poke around with the headers a bit, but since this is managed through getters and setters, the storage format will be mostly invisible.

**Comment by jeremydaly** [comment]
Ah yes! I've been working on ALB support and there is "optional" multi-value header support, so we need to support both, but I'll use your pull request as the base for this.

Thanks!!!

**Comment by jeremydaly** [comment]
Well this is fun. API gateway passes through `headers` and `queryStringParameters` as both strings and multi-values. ALB is one or the other depending on the "multi-value headers" support flag.

**Comment by jeremydaly** [comment]
Parsing REQUEST headers versus formatting RESPONSE headers need to be done differently. I've added a separate `req.multiValueHeaders` property that will allow for more fine-grained control without breaking existing implementations. Headers in the response will use the array format and will be returned based on the interface.

**Comment by brianwthomas** [comment]
Can we reopen this?  I have lambda-api@0.10.1 installed and if multiValueHeaders = null in the event, it returns 

{multiValueHeaders: Object, statusCode: 500, body: "{"error":"Cannot convert undefined or null to object", isBase64Encoded: false}

If I set this value to say "", it resolves this issue.

npm list

+-- aws-sdk@2.415.0
| +-- buffer@4.9.1
| | +-- base64-js@1.3.0
| | +-- ieee754@1.1.8 deduped
| | `-- isarray@1.0.0
| +-- events@1.1.1
| +-- ieee754@1.1.8
| +-- jmespath@0.15.0
| +-- querystring@0.2.0
| +-- sax@1.2.1
| +-- url@0.10.3
| | +-- punycode@1.3.2
| | `-- querystring@0.2.0 deduped
| +-- uuid@3.3.2
| `-- xml2js@0.4.19
|   +-- sax@1.2.1 deduped
|   `-- xmlbuilder@9.0.7
`-- lambda-api@0.10.1

**Comment by jeremydaly** [comment]
I'll take a look. Do you mean if the value is `NULL` or `undefined`?

**Comment by brianwthomas** [comment]
APIGW is setting the value to null

Here's the test event I can use which triggers this (I pulled out all of the other stuff to isolate it down to the headers.

Event:
{ 
"resource": "/bikes/{userId}",
"path": "/bikes/11",
"httpMethod": "GET",
"multiValueHeaders": null,
"pathParameters": 
	{ "userId": "11" },
"body": null,
"isBase64Encoded": false }

Response:
{
  "multiValueHeaders": {
    "content-type": [
      "application/json"
    ]
  },
  "statusCode": 500,
  "body": "{\"error\":\"Cannot convert undefined or null to object\"}",
  "isBase64Encoded": false
}

If I set the value to ""

{
  "multiValueHeaders": {
    "content-type": [
      "application/json"
    ]
  },
  "statusCode": 200,
  "body": "...",
  "isBase64Encoded": false
}

**Comment by brianwthomas** [comment]
for what it's worth. If I set the value of it to undefined, I get similar results. So seems like if APIGW sets it to null (which it does if there's no headers present) then it's erroring out.

**Comment by jeremydaly** [comment]
Thanks for the information.

**Comment by brianwthomas** [comment]
Even more info for you.

So, this error only crops up when doing a test from APIGW using the method execution test (before deploying API)

If I deploy my API and make a request to the RESTful endpoint, I see no issues.

**Comment by brianwthomas** [comment]
Side note, I'll follow up with APIGW on their testing tests to see about making sure they add multiheadervalues there.

**Comment by jeremydaly** [comment]
I've confirmed that a null value fails, so regardless of WHY the value is null (or undefined), the system should catch it. I will add a fix soon.

**Comment by brianwthomas** [comment]
Maybe worth noting that on most entities that are sent, if they're null it errors out. I ran into the same issue with the body null/undefined on a PUT request (I know that's not smart, but it does return a odd error and I feel is an error that the user should be able to handle on their own)

**Comment by ktersius** [comment]
Also running into the issue where null multiValueHeaders will cause an exception.

```
 Cannot read property 'getRemainingTimeInMillis' of undefined","    at Object.context (/var/task/node_modules/lambda-api/lib/logger.js:76:28)","    at Object.log (/var/task/node_modules/lambda-api/lib/logger.js:96:46)","    at REQUEST.logger (/var/task/node_modules/lambda-api/lib/request.js:263:44)","    at Object.fatal (/var/task/node_modules/lambda-api/lib/request.js:54:48)","    at API.catchErrors (/var/task/node_modules/lambda-api/index.js:273:16)","    at API.run (/var/task/node_modules/lambda-api/index.js:240:18)"
```
