### ISSUE TITLE
TypeScript definition inconsistent with Lambda funcionality and lambda-api implementation

### ISSUE THREAD

**Issue by geovanisouza92** [jeremydaly/lambda-api#77]
At [this line](https://github.com/jeremydaly/lambda-api/blob/881325cbaa699243e3657358838707b9fc729737/index.d.ts#L195) the definition doesn't accept the callback param, and returns an anemic type, instead of a promise, breaking general TS type checking, forcing the consumers to cast the return or force the callback param.

Beyond that, the typing is not aligned with the examples in README.

**Comment by harshit-yadav** [comment]
Any update on this ?

**Comment by jeremydaly** [comment]
Hi @geovanisouza92, Typescript support was generously added by members of the community.

I can see the issue with the callback, but can you provide more detail regarding the other examples?

**Comment by geovanisouza92** [comment]
The run method should have the signature:

```typescript
export default class API {
  // ...

  run(event: APIGatewayEvent, context: Context, cb: (err: Error, result: any) => void): void;
  run(event: APIGatewayEvent, context: Context): Promise<any>;

}
```

This way it would be aligned with lambda's `handler` signature and `run` method functionality.
