### ISSUE TITLE
Registering a route without path

### ISSUE THREAD

**Issue by ceilfors** [jeremydaly/lambda-api#78]
I'm using lambda-api for a single purpose function and would not like to duplicate the path information that I have defined in API Gateway. Is there a way I can achieve this?

*Expected (not working)*

```
app.any('/*', async (req, res) => {
  // do something
});
```

*Actual*
```
app.any('/pathThatIHaveDefinedInApiGateway', async (req, res) => {
  // do something
});
```

**Comment by jeremydaly** [comment]
Hi @ceilfors! Wildcard paths only work with defined paths, e.g. you want to apply CORS to all paths. You can use path parameters, like `/:param`, but that will only match one level deep. If you need multilevel, you can just define nested params, like `/:param1/:param2`.

**Comment by ceilfors** [comment]
Hi @jeremydaly! I would like to be able to just register it without defining whether it's a one level deep or multi level. It's a single purpose function and I don't really care about the path when I'm registering them, i.e. when the API gateway path is changed, I don't need to change my code to match the new path definition.

The workaround I have at the moment is to have the registration done dynamically within the handler, which is not ideal as the registration will be running on every handler call.

```js
const convertApigatewayToLambdaApi = resourcePath =>
  resourcePath.replace(/{([^}]*)}/g, ":$1");

module.exports.handler = (event, context) => {
  app.any(convertApigatewayToLambdaApi(event.requestContext.resourcePath), /* ... */)
  return app.run(event, context)
}
```
