### ISSUE TITLE
Add support for ALB traffic

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/lambda-api#80]
See announcement here: https://aws.amazon.com/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/

**Comment by jeremydaly** [comment]
I ran a quick test and most of this looks to be supported out of the box. I need to run some additional tests and figure out where there are discrepancies.

**Comment by jthomerson** [comment]
@jeremydaly maybe this will help: https://serverless-training.com/articles/api-gateway-vs-application-load-balancer-technical-details/

**Comment by jeremydaly** [comment]
@jthomerson, thanks! I discovered quite a bit of this on my own, but great to have this reference.
