### ISSUE TITLE
Support for WebSockets

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/lambda-api#82]
AWS announced native WebSocket support for API Gateway. This should be a fairly simple handshake to upgrade connections to WebSockets, so a convenience method to do this can be easily implemented.

This feature has not yet been released by AWS, but should be coming soon.

**Comment by jeremydaly** [comment]
I played around with the new WebSocket report in API Gateway, but I'm not sure if it makes a ton of sense to add convenience methods for any of this. Still need to play around with binary support and see if that might be useful.

Reference: https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/

**Comment by dalisoft** [comment]
Would be great websocket support at library/framework level
