### ISSUE TITLE
Add requestContext.sourceIp fallback for missing x-forwarded-for

### ISSUE THREAD

**Issue by nickmeldrum** [jeremydaly/lambda-api#85]
The `REQUEST.ip` property is mapped from the `x-forwarded-for` header instead of the `sourceIp` property on the `event.requestContext` property.

Can you give me the info about why?

The problem I have is when running this in serverless-local to emulate a lambda locally for my testing, the ip comes through as undefined.

**Comment by jeremydaly** [comment]
Hi @nickmeldrum,

The `x-forwarded-for` is the standard way to extract IP addresses from a proxy so it was implemented that way. This also works with the new ALB routing (which doesn't have an IP address as part of the request context).

However, I can see the issue with your local use case, so I can add a fallback if the `x-forwarded-for` is undefined or null.

Thanks for the report.

- Jeremy

**Comment by nickmeldrum** [comment]
interesting thanks - is it right for you to add a fallback or for the `serverless-local` package to correctly set the `x-forwarded-for` header i wonder?

**Comment by jeremydaly** [comment]
Good question, probably the latter. However, I'm adding support for Lambda@Edge functions as well, and according to this documentation (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html#lambda-event-structure-request), those events don't contain `x-forwarded-for` either.

There may need to be a number of fallbacks to normalize the client IP address, so I think it would be worth adding.

**Comment by nickmeldrum** [comment]
good info cheers
