### ISSUE TITLE
Thoughts on serving static files?

### ISSUE THREAD

**Issue by ToddHoff** [jeremydaly/lambda-api#86]
First,  lambda-api is great. So useful. Thanks!

 One thing I didn't see is the static file serving equivalent in express. That is:

`app.use(Express.static(Path.join(__dirname,'public')));
`

Any thoughts on how best to do this?

**Comment by compwright** [comment]
I don't understand why you would do this. Wouldn't it be better to serve the static files from AWS S3? You can mount that onto the URL path of your choice using API Gateway.

**Comment by jeremydaly** [comment]
@ToddHoff, sorry for jumping in late here. There are several ways to serve static files with Lambda API. You can use the [sendFile method](https://github.com/jeremydaly/lambda-api#sendfilefile--options--callback), which can serve a file that is packaged with your function. So if you wanted to serve a `favicon.ico`, for example, you could package that with your Lambda function and serve that up.

If you are serving larger files, or ones that might change often, you can serve them *through* Lambda API, but host them in S3. You would use the `sendFile` method for that as well, but just use the `s3://my-bucket/path/to/file.png` filename format and it will transfer the file from S3 and serve it through API Gateway. This allows you to serve files with a URL like `https://myapigatewaydomain.com/somefile.pdf`.

If you are serving really large files, like a PDF or executable download, then you are better off using the [getLink](https://github.com/jeremydaly/lambda-api#getlinks3path--expires--callback) method to retrieve a signed URL for objects in an S3 bucket. You can then use the `download` method if you want to prompt a download, or `redirect` if you want them to load it in the browser (assuming it's possible with the file type). You could, in theory, use the `getLink` method to serve up static files in this way also. If you requested an image, for example, it would be possible to use a combination of `getLink` and `redirect` to have a browser load the file.

With all that said, I agree with @compwright. The better way to serve static files is to add something like an `/assets` folder with an S3 origin to your API Gateway CloudFront distribution. But I do believe there are times that serving files through Lambda API makes sense.

Hope that helps,
Jeremy

**Comment by ToddHoff** [comment]
> You can use the sendFile method, which can serve a file that is packaged with your function.

Yep, that's what I did. Though SAM local seems to pick them up directly from under the public directory.

And thanks for the other suggestions. I'll keep them in mind.

> With all that said, I agree with @compwright. 

Certainly, no doubt. Part of the issue is it would be cool to test locally by going back and forth between express and lambda-api. It's very close I think.

**Comment by jeremydaly** [comment]
Let me think about this more. Not sure why SAM local would pick it up from the wrong directory, but I'll take a look.

**Comment by ToddHoff** [comment]
I think it's just something SAM local does automatically. Though I really have no idea what I'm doing. You can specify where it can find static files. My guess is if it sees a public directory it just does the right thing. It's something I discovered by accident.

**Comment by hjrobinson** [comment]
I feel like an idiot for overlooking the obvious, but I thought I would mention this anyway in case someone has the same issue.  If you're using a view engine like pug set your hrefs equal to the urls of the css files in your S3 bucket or the urls of the routes that use the sendFile method.
