### ISSUE TITLE
Add support for creating multiple cookies

### ISSUE THREAD

**Issue by brighttank** [jeremydaly/lambda-api#90]
In the current implementation setting one cookie will override any previously set cookie.

However, it's quite common to need to set multiple cookie, Eg. a session cookie and a CSRF cookie.

It would be nice to be able to do:
response.cookie('session', 'value', {httpOnly: true});
response.cookie('csrf', 'value, {httpOnly: false});

**Comment by jeremydaly** [comment]
Hi @brighttank,

This has been addressed in #73 and will be available in v0.10 which should be released soon.

Thanks,
Jeremy

**Comment by brighttank** [comment]
Fantastic. Keep up the good work!
