### ISSUE TITLE
path.trim is not a function

### ISSUE THREAD

**Issue by cwhiteley** [jeremydaly/lambda-api#94]
I have this code running within AWS  us-east-1

const api = require('lambda-api')({ version: 'v1.0', base: '/v1' })

api.get('/status', (req,res) => {
  return { status: 'ok' }
})

module.exports.router = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false
  console.log(event)
  api.run(event, context, callback)
}

The logs show no errors.  The full event is published to logs. 

I get this response:

`{
    "headers": {
        "content-type": "application/json"
    },
    "statusCode": 500,
    "body": "{"error":"path.trim is not a function"}",
    "isBase64Encoded": false
}`

**Comment by jeremydaly** [comment]
Does the `event` contain a `path` property?

**Comment by cwhiteley** [comment]
Thanks to Jeremy's assistance - the issue is that we have set the integration element within the serverless.yml file.

`- http:
          path: 'v1/{proxy+}'
          method: any
          integration: lambda
          cors: true`

the integration element is incorrect.  It should be removed completely or set to lambda-proxy which is the default.
