### ISSUE TITLE
Perform logging after Error middleware has executed

### ISSUE THREAD

**Issue by brighttank** [jeremydaly/lambda-api#98]
Currently the catchErrors function logs the error before calling the error middleware. This prevents the middleware from setting values that may be relevant to what's logged, eg. the response code.

My handlers throw custom Errors such as ValidationError, AuthError, etc which I then handle in my middleware to set the HTTP response code but the values I set there are not logged properly due to the way the catchErrors function currently works.

Seems like it would be easy enough to move the logging to after the middleware is processed. Would just have to make sure that we didn't clobber the statusCode doing to following:
`      response.status(code ? code : this._errorStatus)`

**Comment by jeremydaly** [comment]
Hi @brighttank,

Logging is performed after the error middleware is fired, but the status code is not getting passed correctly to the final log. I am investigating this.

Thanks for the report,
Jeremy

**Comment by jeremydaly** [comment]
After reviewing this, the current set up makes it a bit difficult to move the error logging after the error middleware. I have some ideas how to handle this, but it requires a small rewrite of how errors get caught and stored. I have fixed the incorrect status code issue, and am merging that in.

**Comment by brighttank** [comment]
Would moving the logging to after the for loop not work?
```

  async catchErrors(e,response,code,detail) {

    // Error messages should never be base64 encoded
    response._isBase64 = false

    // Strip the headers (TODO: find a better way to handle this)
    response._headers = {}

    let message

    // Set the status code
    response.status(code ? code : this._errorStatus)

    // If first time through, process error middleware
    if (response._state === 'processing') {

      // Flag error state (this will avoid infinite error loops)
      response._state = 'error'

      // Execute error middleware
      for (const err of this._errors) {
        if (response._state === 'done') break
        // Promisify error middleware
        await new Promise(r => {
          let rtn = err(e,response._request,response,() => { r() })
          if (rtn) response.send(rtn)
        })
      } // end for
    }

    /*
     * Moved from above for loop
    */
    let info = {
      detail,
      statusCode: response._statusCode,
      coldStart: response._request.coldStart,
      stack: this._logger.stack && e.stack || undefined
    }

    if (e instanceof Error) {
      message = e.message
      this.log.fatal(message,info)
    } else {
      message = e
      this.log.error(message,info)
    }

    // Throw standard error unless callback has already been executed
    if (response._state !== 'done') response.json({'error':message})

  } // end catch

```
